{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-petclinic.database.fullname" . }}
  labels:
    {{- include "spring-petclinic.database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "spring-petclinic.database.selectorLabels" . | nindent 4 }}
{{- end }} 