{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-petclinic.database.fullname" . }}
  labels:
    {{- include "spring-petclinic.database.labels" . | nindent 4 }}
type: servicebinding.io/postgresql
stringData:
  type: "postgresql"
  provider: "postgresql"
  host: "{{ include "spring-petclinic.database.fullname" . }}"
  port: "{{ .Values.database.service.port }}"
  database: "{{ .Values.database.auth.database }}"
  username: "{{ .Values.database.auth.username }}"
  password: "{{ .Values.database.auth.password }}"
{{- end }} 